### ISSUE TITLE
In-Game-Round Mini-Map

### ISSUE THREAD

**Issue by Tapsi** [ctomni231/cwtactics#114]
# Description

As a gamer I want to view the whole map on the screen without having to move through the map to get a small overview about the current  state of the battle. 

# Links to other issues

- requires #379 and #380 

# Tasks

- [ ] The minimap opens by pressing B on an empty field
- [ ] The minimap is in front of all
  - [ ] Show Player objects
    - [ ] Colored symbols for units
    - [ ] Colored symbols for properties
    - [ ] Color based on the object owner
  - [ ] Use red border for the visible screen 
- [ ] Move through the minimap with b (aka fast move)
- [ ] Move cursor normally
- [ ] Update screen borders when screen moves
