### ISSUE TITLE
Automatic Error Reporting

### ISSUE THREAD

**Issue by CRamsan** [ctomni231/cwtactics#340]
# Description

It would be very nice to have some way to automatically keep track of errors and exceptions in the game. 

As an example of this system is the ACRA project (https://github.com/ACRA/acra) for Android. This will basically catch all the exceptions and generate a report with the important information(stack trace, environment, OS, etc) and it will be delivered to either an email, google doc or a custom website. 

The nice thing about this is that allows to keep very detailed statistics about bugs and their priority. 
# Links to other issues
- requires #379  
# Tasks
- [ ] When an error is thrown, then the game goes into an error state which contains the error message and some action buttons
  - [ ] Button to dismiss the error and reload the game
  - [ ] Button to report the error (to the official error page) and reload the game

**Comment by Tapsi** [comment]
@ctomni231 Is it enough to submit a hidden form with named input fields as POST action with [http://battle.customwars.com/report/index.php](http://battle.customwars.com/report/index.php) as target ?

**Comment by ctomni231** [comment]
Yeah, we can just post a form that gives an error message. No need to go too crazy with the implementation. We already are very generous with the way people can post errors to the system. (Hopefully users won't want to hurl rocks at me in the future for this :disappointed_relieved:
