### ISSUE TITLE
Assets must be checked 

### ISSUE THREAD

**Issue by Tapsi** [ctomni231/cwtactics#375]
# Description

When all assets are loaded then we should check that every displayable game object and every misc. object for the menus contains a valid graphic in the sprite database.

# Tasks

- [x] Throw an error when the assets are not valid
- [x] Object types can annotated to be validated after created
- [x] Validation of object types during load process
