### ISSUE TITLE
Game Refactoring

### ISSUE THREAD

**Issue by Tapsi** [ctomni231/cwtactics#379]
# Description

As a developer I want to make sure that CWT runs fine across different device types _(Desktop and Mobile)_ to give CWT a much greater base of usable devices. Furthermore I want to make sure that it is maintainable by more than one developer because it's current size is too big to be maintained by one single developer.

Ready at: **end april - mid may**

# Links to other issues

- requires #380 #401 

# Acceptance Criteria

###  Tasks for WolfTec

- [x] STJS - Proof of Concet
  - [x] Add ST-JS library
  - [x] Test ST-JS maven compiler plugin _(Works with Eclipse 4.4)_
  - [x] Do some compilation tests with ST-JS
- [x] Pathfinding 
  - [x] Basic API
  - [x] A* algorithm 
- [x] State machine
  - [x] Simple API without heavy inheritance 
  - [x] State class itself has methods to access the state machine
  - [x] Send state machine as parameter in the update method ```update(StateMachine stm, int delta)```
- [x] Audio System
  - [x] Audio API
  - [x] WebAudio Backend
- [x] Network System
  - [x] Drop buffers from network system and send messages directly into the action system
  - [x] Make the network messages abstract _(game will handle)_
- [x] Localization enhancements
  - [x] Support more languages
  - [x] Loads only the active language into the RAM
  - [x] Load language by browser configuration
  - [x] Support common language synonyms (e.g. en ist same as en_us, en_gb)
- [x] Decision trees to build up AI players
  - [x] DecisionTree
  - [x] Node
  - [x] Sequence breaks when one node returns fail
  - [x] Executes a random choosen action
  - [x] Selector breaks when one node returns success
  - [x] Inverter 
  - [x] LoopUntilFail 
  - [x] Repeater 
  - [x] Task 
- [x] Persistence 
  - [x] VirtualFilesystem to have an abstract access data
  - [x] VirtualFilesystemFolder to have an abstract access to a folder of the VFS _(e.g. like /units)_ 
  - [x] VfsFolderObjectFactory which creates VFS folders based on an annotation in a bean
  - [x] HtmlVFS
    - No write support
    - Uses XmlHttpRequest
    - Supports different file types 
  - [x] LocalForageVFS
    - Does everything ^^
  - [x] Ability to set a converter object
  - [x] Ability to set a validation object
- [x] Enhance input system
  - [x] Decoupled input backends
  - [x] Realize input key to action mapping 
  - [x] Configurable input manager
- [x] Graphic engine
  - [x] Layered system which merges into one layer
  - [x] Better sprites with sprite sheet support
  - [x] Screen moving
  - [x] Basic GUI mechanic 
    - [x] UiElement which contains a custom render method _(abstract)_
    - [x] UiImage which contains a image to be rendered
    - [x] UiAction which contains a image to be rendered, text and an action id
    - [x] Extend menu state by a ```action(String actionId)``` method
    - [x] UiLayout which contains many UiElements in a grid
- [x] BeanFactory
  - [x] *Dependency injection* and *Inversion of Control* with a bean concept 
  - [x] Mini resolver to parse common expressions in bean related annotaions (e.g. ```$options.myVar``` searches for myVar in the options object)
  - [x] Complete bean creation
  - [x] Complete dep. injection
  - [x] Complete creation by object factories
  - [x] Ability to prevent the instantiation of given bean classes
- [x] DataObject validation
  - [x] Validation annotations
  - [x] Ability to cache the validations per class
- [x] DataObject serialization
  - [x] Serialization annotation
  - [x] Utility class to serialize and deserialize data from / into that objects
  - [x] Ability to cache the serialization per class
  - [x] Ability to set custom serializer class
- [x] Get rid of the old XmlHttp API

### Tasks for CWT
 
- [x] Game logic update _(Concept needed)_
- [x] Move state data model into states where possible and useful
- [x] Java integration
  - [x] Add ST-JS library
  - [x] Test ST-JS maven compiler plugin *(Works with Eclipse 4.4)*
- [x] Localization enhancements
  - [x] Options to select a language
- [x] GameData formats
  - [x] Object types
  - [x] Network message type
  - [x] Game objects
  - [x] Connect validation steps
- [x] Remove of the old action system
  - [x] Should be handled by a bean because the old actions maps already to the game logic. In this case mapping process data object to command execution and vise versa should be more abstract and done in a central way. The game logic does the model changes.
  - [x] More dynamic action data objects (rethink)
- [x] Refactor savegame manager 

###  Tasks for WolfTec

- [x] Merge wCore and wPlay again into the wolfTec-Engine
- Container
  - [ ] ```CircularList```
  - [ ] ```CircularBuffer```
  - [ ] ```Matrix```
  - [x] Interface ```List```
  - [ ] Interface ```Buffer```
  - [X] ```Pagination``` ⇒ ```Constructor(list)```
  - [ ] ```PositionableMatrix``` ⇒ ```Constructor(list)```
- Test
  - [x] Interface ```TestRunner```
    - [x] ```loadAll(cb)```
    - [x] ```runAll(cb<List<???>>)```
  - [ ] Simple class ```UnitTestrunner```
  - [ ] Asserts
    - [x] ```assertTrue(expr, msg)```
    - [x] ```assertFalse(expr, msg)```
    - [x] ```assertEmpty(list, msg)```
    - [x] ```assertNotEmpty(list, msg)```
    - [ ] ```assertFull(list, msg)```
    - [x] ```assertEq(a, b, msg)```
    - [x] ```assertSame(a, b, msg)```
  - [ ] Test Class
    - [ ] ```@Before```
    - [ ] ```@BeforeClass```
    - [ ] ```@After```
    - [ ] ```@AfterClass```
- Core
  - [ ] No automatical management of internal components
    - [ ] Manual instantiation with ```manager.onPreInit( )```
    - [ ] Helper to init internal components ⇒ ```manager.autoInitInternalComponents( )```
  - [x] ~~Interface InjectsCode~~ _(Can be done with JSEU and onComponentConstruction)_
    - Will be used to insert 3rd party dependencies
    - [x] ```injectCode( )```
    - [x] manager injects this code into the runtime environment
- Persistence
  - [x] ```VFS``` ⇒ ```ResourceLocation``` ???
  - [x] ```HtmlReadOnlyStorage``` ???
  - [x] ```LocalForageStorage``` ???
  - [x] ```FileStorage``` ???
  - [x] A view would be nice like  ```@ResourceLocationView(folder=”/xyz”, converter=X.class, serializer=Y.class)```
- Log
  - [x] ```NullLogger``` (writes nothing)
  - [x] ```Logger``` ⇒ ```onConstruction(Instance, ClassName)```
- i18N
  - [x] ```SimpleLocalizationProvider```
  - [x] ```LocalizationManager``` ⇒ ```LocalizationProvider```
- Util package with utility classes
  - [x] ```ContainerUtil``` ⇒ ```CU```
  - [x] ```BrowserUtil``` ⇒ ```BU```
  - [x] ```JsUtil``` ⇒ ```JU```
  - [x] ```PerformanceUtil``` ⇒ ```PU```
  - [x] ```ConvertUtility``` ⇒ ```CVU```
  - [x] ```ReflectionUtil``` ⇒ ```RU```
  - [x] ```MU``` (MapUtility)
    - [x] ```getDistanceByPosition(x, y, tx, ty)```
    - [x] ```getDirectionByPosition(x, y, tx, ty)```
    - [ ] ```getPositionCodeByPostion(x, y)```
    - [ ] ```getXByPositionCode(code)```
    - [ ] ```getYByPositionCode(code)```
- Usage of a variable naming pattern
  - [ ] ```pVarname``` ⇒ Instance variable (bspw. ```pHiddenVar``` ) ⇒ especially for stjs
  - [ ] ```lVarname``` ⇒ Local variable like in a method (bspw. ```lDistance``` )
- Remove fnc package
- [x] ```Pathfinder``` ⇒ Interface
- Network
   - Disconnect / Connect ⇒ As API or is that better be realized via commands ?
- Loader
  - [x] ```ElementLoadedListener``` ⇒ ```LoadingListener```
  - [x] ```GameLoadingHandler``` ⇒ ```LoadingHandler```
  - [x] ```GameLoadingManager``` ⇒ ```LoadingManager```
- GUI … 
- Gfx
  - [x] Move ```Direction``` out of ```DirectionUtil```
  - [ ] Remove ```SpriteSizeMetric``` ⇒ Backt to the simple left to right model with index access
  - [x] ```ImageManipulationManager``` ⇒ ```IU``` (ImageUtil: static, no managed component)
- Input
  - [x] ```LiveInputManager ⇒ ```StatefulInputManager```
  - [x] Interface ```InputManager```

### Tasks for CWT

- [ ] Java integration ⇒ Convert current source code to java source code
- [ ] GameData formats
  - [ ] Map file type
  - [ ] Implement random security check in the workflow
- [ ] Add old game states
- [ ] ```EGU``` which extends ```GU``` (ExtendedGameUtility) 
  - [ ] ```getTileByPositionCode(code)```

### Both

- [ ] Fix all ```TODO``` marks
