### ISSUE TITLE
Enhance Dumbboy 

### ISSUE THREAD

**Issue by ctomni231** [ctomni231/cwtactics#381]
# Description

The next version of DumbBoy should be a lot smarter by creating a good set of rules.

[Implementation of Dumbboy] (https://github.com/ctomni231/cwtactics/tree/master/gameSrc/net/wolfTec/ai)

# Links to other issues

- requires #379 

# Tasks

- [x] Changes in WolfTec
  - [x] Add HSM like elemens *(Sequence, All, OneOf, Random, Inverted, BreakIfCancel, etc.)* to the current state machine class
- [ ] Changes in CWT
  - [ ] Ends turn when no actions are left
  - [ ] Builds units
  - [ ] Captures neutral and enemy properties
  - [ ] Stops enemy capture process
  - [ ] Uses a ratio like system to check what should be attacked or built

**Comment by Tapsi** [comment]
Prepared a first bunch of APIs 

[API](https://github.com/Tapsi/wolfTecEngine/tree/master/engineSrc/org/wolfTec/wolfTecEngine/decision)

[Sample Action](https://github.com/ctomni231/cwtactics/blob/master/gameSrc/org/wolfTec/cwt/game/ai/SampleHello.java)
[Sample Bean with DecisionTree](https://github.com/ctomni231/cwtactics/blob/master/gameSrc/org/wolfTec/cwt/game/ai/ArtificialInteligenceBean.java)

**Comment by Tapsi** [comment]
Complete the wCore.js and wPlay.js until 24.04.2015
