### ISSUE TITLE
Play Attack Sounds

### ISSUE THREAD

**Issue by ctomni231** [ctomni231/cwtactics#383]
# Description

Play sounds during attacks.

# Tasks

- [ ] Add a *Tank - Cannon* sound that will be used by tanks
- [ ] Add a *Rockets* sound that will be used by rocket units
- [ ] Add a *Flak* sound that will be used by AA cannons
- [ ] Add a *Machine Gun* sound that will be used by infantries
- [ ] Play attack sounds during the attack action
