### ISSUE TITLE
Enhance input mechanics

### ISSUE THREAD

**Issue by ctomni231** [ctomni231/cwtactics#384]
# Description

Some stuff does not works good like expected.

# Tasks

- [x] GamePad input should work in Chrome
- [x] Force touch mode per URL parameter must work 
- [x] The mapping of the  input backends will be loaded at start of the game engine 
- [x] Simple button scheme ( A, B,  LEFT, RIGHT, UP, DOWN, PIN_AT... )
