### ISSUE TITLE
Implement In-Game Animations

### ISSUE THREAD

**Issue by ctomni231** [ctomni231/cwtactics#385]
# Description

Combined Five separate points into one feature request issue. Changed the name to Implement In-Game Animations.

# Links to stories

- Cannot started until #379 and #380 is finished.

# Tasks

- [x] Implement AW2 rain weather animation
- [x] Implement AW2 snow weather animation
- [ ] Implement destroy unit animation
- [ ] Implement move TRAP! animation
- [ ] Implement repair unit animation
- [ ] Implement supply unit animation
