### ISSUE TITLE
Implement Debug Bean

### ISSUE THREAD

**Issue by ctomni231** [ctomni231/cwtactics#389]
# Description

As a developer I want to get information about the game without having to deal with console commands every time.

# Tasks

- [ ] Implement as additional bean that can be added or removed to the game files
- [ ] Shows or Hides a debug information screen on the screen with information about the game data
- [ ] Debug class 
  - [ ] reloadActiveMap(callback) => Reloades the active map

**Comment by Tapsi** [comment]
@ctomni231 Please add the needed debug API here :)
