### ISSUE TITLE
(01.06.15 - 31.06.15) Device Regression Tests

### ISSUE THREAD

**Issue by ctomni231** [ctomni231/cwtactics#390]
# Description

Will be done at last

# Links to other issues

- Complete the **WolfTec Gherkin Test-Runner** for **Sprint 39**. 

# Tasks

- [ ] On iPhone 5(c) _(or equivalent architecture)_
- [ ] On Surface Pro 3 _(Chrome, Safari, Firefox, IE)_
- [ ] On Nexus 7 _(2013 edition)_
