### ISSUE TITLE
(31.06.15) Sprint Release + Retroperspective

### ISSUE THREAD

**Issue by ctomni231** [ctomni231/cwtactics#391]
# Description

This is the last action after testing

# Tasks

- [ ] Web-Version (Browser)
- [X] ~~NodeWebkit-Version (Mac, Windows, Linux)~~
- [ ] Prepare website data for 0.38 (Text,Changelog)
- [ ] Create release on github
