### ISSUE TITLE
Wunderlist To-Do - Network Server

### ISSUE THREAD

**Issue by ctomni231** [ctomni231/cwtactics#394]
- [x] **First Brainstorming**
- [x] **Study deeply into how WebSockets work to get a basic implementation for nodeJS**
- [x] **Write up a javascript implementation of nodejs server**
- [x] **Get a basic server implementation within the local repository**

These are different server architectures that we can strive for when designing.,,
- Prospect Server - 10GB File Limit
- Current Bandwidth - www.dreamhost.com/servers/compare-our-products/
- Prospect Forum - 2GB File Limit
- Prospect Front Page - 3GB File Limit
- Openshift
