### ISSUE TITLE
Wunderlist To-Do - Zooming Feature

### ISSUE THREAD

**Issue by ctomni231** [ctomni231/cwtactics#395]
Change the base tile size to generate a valid zooming

- [ ] screen.setScale( factor )
- [ ] Set the tile base to 8,16 or 32 pixel
- [ ] Screen has to use the given base size
