### ISSUE TITLE
Touch Device "Natural" Menu Organization

### ISSUE THREAD

**Issue by ctomni231** [ctomni231/cwtactics#396]
# Description

To make the menus of CWT adhere closer to the menus of the original series, some steps are going to be taken to make the menus more fluid and natural for the user base. The menu will be able to be displayed in two ways as outlined below.
- **Center Position:** The menu positions to the center of the visible map. Any click outside the menu borders counts as cancel.
- **Cursor Position:** The menu positions relative to the cursor position (usually bottom right) depending on where the cursor is on the map. The locations for the menu position can be on the top left, bottom left, top right, bottom right depending on if the menu will be outside the borders of the map.

In addition to this, menu position will be fixed depending on the type of menu. This will make the menus flow exactly close to the grain of the original games, and hopefully also eliminate any UI issues present in the past. 

[BlackCat - Links](https://www.javascripting.com/mobile-and-touch/)

**Center Position** 

Center it in the middle of the screen

http://lparchive.org/Advance-Wars-Dual-Strike/Update%2009/36-Sky24.png
http://www.cubed3.com/staff/tempo88/aw_review2.jpg

**Cursor Position**

http://images.nintendolife.com/screenshots/9098/large.jpg
# Links to stories
- Needs #379, #384 
# Tasks
- [ ] Main Menu (End Turn, CO Powers, Options) - Center Position
- [ ] Build Menu (Airport, Bases, Seaport) - Center Position
- [ ] Invention Action Menu (Fire Cannon, Attach CO) - Cursor Position
- [ ] Unit Action Menu (Attack, Capture, Move, Wait) - Cursor Position
