### ISSUE TITLE
Wunderlist To-Do - Longterm Ideas

### ISSUE THREAD

**Issue by ctomni231** [ctomni231/cwtactics#397]
A place to hold a lot of long term ideas that aren't in any sort of planning cycle. 

**Long - Term Plans**
- [ ] Biome based map generator
- [ ] Create custom Commander feature
- [ ] Modification support
- [ ] In-Game SDK

**Developer planning**
- [ ] Split project into smaller modules
- [ ] Split binary assets into separate downloadable packages away from Github
- [ ] Look into Github releases

**What We've Done (Recently)**
- [x] Wrote an extractor to pull maps from AWN Map Page & AWBW Map Page
- [x] Found the file that is necessary to convert maps into CWT maps

**Extra Notes (Future TODO)**
- [ ] Have AI or extra player take over for dead players in Network Mode
- [ ] Include both positive and negative tags for sorting Map Selection Data
- [ ] Mute Option for Chat

**Important Stuff (3 Things Needed for CWT)**
- [ ] The Network
- [ ] The Correct Damage Formula
- [ ] The CO's Working 

**Quotes (for Fun)**
- *"Coooooool! :D" - BlackCat*
- *"Users only care about what **ISN'T** done, not what is." - JSRulz*
- *"Every noble work is at first impossible" - Carlyle*
