### ISSUE TITLE
Wunderlist To-Do - Community Tasks

### ISSUE THREAD

**Issue by ctomni231** [ctomni231/cwtactics#399]
These are tasks specifically for community related issues. 

_For completion, I'm listing it in here, but a place should be designated for these types of tasks in the future. This is a one time issue just for completion of transfer from one spot to another._
- [x] Work on Map Converter for Maps
- [x] Work on Blog Message for Art
- [x] Do a bit of Research on Twitter (OzRamos)
- [x] [Work on AW2 Commanding Officer Statistics](http://forums.customwars.com/viewtopic.php?f=117&t=13636)
