### ISSUE TITLE
Wunderlist To-Do - Graphic Tasks

### ISSUE THREAD

**Issue by ctomni231** [ctomni231/cwtactics#400]
Various Graphic Tasks for Server, Webpage, and Game

- [ ] Finish the Keyboard Graphics (Network Task)
- [ ] Begin Framework for the Network Graphic (Heading for KISS method)
- [ ] Work on Commanding Officer Images
- [x] Produce a graphic for the in-map cursor
