### ISSUE TITLE
GameEngine should use the pattern "Inversion of Control" and "Dependency Injection"

### ISSUE THREAD

**Issue by Tapsi** [ctomni231/cwtactics#401]
**Concept:** 

It's always better to set class instance dependencies from outside by a given set of requirements _(less coupling between classes)_. 

We create a special pattern to allow _dependency injection_. The mediator class instantiates, like before, all necessary game objects as modules _(called bean from now on)_. Unlike before they will be put into a map. 

Every bean has properties. Some properties starts with a **$** character. They are references to other beans. This kind of properties will be filled automatically with the correct beans after game initialization. As example if you have a property **$gameround** in you bean, then the mediator looks into his bean map and injects the bean **gameround** as value.

**Tasks:**
- [x] `CustomWarsTactics` class instantiates all beans
- [x] `CustomWarsTactics` class has a method to inject all dependencies
- [x] Beans are allowed to have reference properties
