### ISSUE TITLE
Enhancements for the next version

### ISSUE THREAD

**Issue by Stef569** [ctomni231/cwtactics#402]
# Description

This is a list of things that could be improved: Most of them are really small changes
Select map should show the name of the map without the .json
Player configuration shows 4 slots where only 2 are active. Best to only show the amount of slots for the amount of players in the game.

When the game starts I'm greeted with:
Day 0 - Null
It should say Day 1, only developers start counting from 0
Null seems to be the player name, could that be changed to defaults like "Player 1"

Could the game be centred in the browser, and maybe the background set to a dark color so that the contrast is not so high.

The menu is shown in the center of the screen, it should display near the cursor. Because it takes a lot of mouse movement to get to the menu and back to the game.

Looking good. Keep up the good work!

# Links to other issues

- requires and may obselete in some parts by #379 
- Menu positioning will be affected by #396 

# Tasks

- [ ] Map names in the map selection should be shown without the file extension
- [ ] Drop disabled player slots in the game round configuration screen
- [ ] Day counter message should be correct (Day 1,2,3... N)
- [ ] Center map on the screen when the map is smaller than the screen itself
- [ ] More intuitiv menu positioning

**Comment by Tapsi** [comment]
will be fixed by #421
