### ISSUE TITLE
(28.04.15) Review of the active sprint 

### ISSUE THREAD

**Issue by Tapsi** [ctomni231/cwtactics#405]
# Members:
[Blackcat](https://github.com/Tapsi)
[JSRulz](https://github.com/ctomni231)

# Tasks

- [ ] Review completed issues
- [ ] Discussion about left issues
- [ ] Move issues that can't completed in the active sprint to the next sprint
- [ ] Feedback round about the active sprint *(Good things, drawbacks, discussions.. what we should do in the same way again and what we should do in different way next time)*

**Comment by ctomni231** [comment]
Major questions regarding the Sprint ( taking a hint from agile development)...

1. What discipline methods and development methods worked while doing this sprint?
2. What discipline methods and development methods did not work while doing this sprint?
3. What do we need to focus on in the next upcoming sprint to make it feasible to accomplish?

**Comment by Tapsi** [comment]
@ctomni231 Perfect yes. I think I will take the moderation of this first review. As preparation we should look into our stories and should think about:

1. What is complete here ?
2. What is missing ?
3. Is it possible to solve it in this sprint `?
