### ISSUE TITLE
Engine - Tasks Version 0.36

### ISSUE THREAD

**Issue by Tapsi** [ctomni231/cwtactics#424]
## Tasks

- Rewrite data loader
  - [x] Custom error handling
  - [x] Serial queing with async support _(may load several ressources at once)_
  - [x] remove that nasty baton sh**
- [x] Fix recoloring in firefox browser
- [x] Fix game assets configuratuion
- [x] Evaluate possible test management system
- Rewrite action system
  - [ ] Actions has a render_by_data function
  - [ ] Actions has a update_model_by_data function
  - [ ] Actions never trigger events (except temporary to protect legacy code)
  - [ ] Move event based code into the above functions of the actions 
- Model Service API _(MSA)_
  - Inbound-Trigger (`aka client_event_[.]*`)
    - **Description:**  The game UI can push information into the game engine like when a player joins a room or a game will be closed due a leaving hoster. In this case we don't want to let the  game engine know internals about thge UI techniques. Instead we give the UI some API to change the model `like client_event_game_ends(parameter_tbd)`
    - **API:**
      - _Note: An API point can be marked as done if the API itself is implemented in the brigde as well used in the model_
      - [ ] `client_event_player_joins_battle(player_id, player_type, name)`
      - [ ] `client_event_player_leaves_battle()`
      - [ ] `client_event_prepare_battle(map)`
      - [ ] `client_event_start_battle()`
  - Outbound-Trigger (`aka. game_event_[.]*`) 
    - [ ] Model triggers changes in the event bridge 
    - [x] Graphic can place own functions in the bridge to react on model events 
    - [ ] Remove existing event system
    - **API:**
      - [ ] `game_event_unit_attacks(attacker_id, attacker_x, attacker_y, defender_id, defender_x, defender_y)`
      - [ ] `game_event_unit_will_be_attacked(unit_id, unit_x, unit_y)`
      - [ ] `game_event_unit_lost_health(unit_id, x, y, lost_health, current_health)`
      - [ ] `game_event_unit_destroyed(unit_id, x, y)`
      - [ ] `game_event_unit_builded(factory_id, unit_type, owner_id, x, y)`
      - [ ] `game_event_unit_leveled_up(unit_id, level)`
      - [ ] `game_event_units_joined(source_unit_id, target_unit_id, target_x, target_y)`
      - [ ] `game_event_unit_moved(unit_id, start_x, start_y, end_x, end_y, way)`
      - [ ] `game_event_turn_changed(day,** turn, turn_owner_id)`
      - [ ] `game_event_weather_changes(weather_id, duration)`
      - [ ] `game_event_modified_player_power(player_id, change, new_value)`
      - [ ] `game_event_player_activates_power(player_id, power_level)`
      - [ ] `game_event_fire_rocket(silo_id, unit_id, silo_x, silo_y, target_x, target_y)`
      - [ ] `game_event_load_unit(transporter_id, load_id, transporter_x, transporter_y)`
      - [ ] `game_event_unload_unit(transporter_id, load_id, transporter_x, transporter_y, unload_direction)`
      - [ ] `game_event_unit_captures(property_id, capturer_id)`
      - [ ] `game_event_property_captured (property_id, new_owner_id, capturer_id)`
      - [ ] `game_event_tile_is_visible(tile_x, tile_y)`
      - [ ] `game_event_tile_is_not_visible(tile_x, tile_y)`
- [x] Merge client and engine source together 
- [x] Turn all code into a flat namespace 
  - **Variant A:** `logic.xyz, model.xyz, controller.xyz` and `view.xyz` 
  - **Variant B:** `do_xyz, xyz_data, control_input_xyz` and `view_xyz` 
- ~~Allow assertion statements to be deletable in live builds~~ _(only directory test will be removed in live build... code should be tested with tests rather than doing thousands of assertions everywhere)_
- [x] Implement a storage API which uses `localforage`
- [ ] Remove old 3rd party libraries
  - [ ] lawnchair*.js
  - [ ] params.js
  - [ ] workflow.js
  - [ ] animFrame.js
- [ ] Graphic API which builds the old html based gui but can be replaced later with @ctomni231 canvas only version
  - [ ] Get rid of static html files
- [x] Add game updater

**Comment by Tapsi** [comment]
Will be replaced by new smaller issues
