### ISSUE TITLE
Replace Lawnchair with LocalForage

### ISSUE THREAD

**Issue by Tapsi** [ctomni231/cwtactics#425]
### Description

Localforage is far more efficient and failsafe for many storage backends (like WebSQL, IndexedDB or localStorage). Because of this we should rather use Localforage than updating Lawnchair.

### Tasks

- [x] Create storage provider module which realizes an **abstract API** (`save, load, delete, deleteAll`) for the persisted game storage
- [x] The storage provider uses **LocalForage** as backend
- [x] Replace existing usages of Lawnchair with the new storage provider
- [x] Remove lawnchair libraries from external js libraries directory
