### ISSUE TITLE
Implement a new state machine module

### ISSUE THREAD

**Issue by Tapsi** [ctomni231/cwtactics#427]
### Description

We need a new state machine which is usable for the whole game. Furthermore it inplement use the `init(), update(...), render(...)` API.

### Tasks

- [x] Add API to register game states

      `cwt.gamestate_register_state(id, state_parameters)`

- [x] Add API to get the active state

      `cwt.gamestate_get_active_state()`

- [x] Add API to set the active state

      `cwt.gamestate_set_active_state(id)`

- [x] Add API to update the active state

      `cwt.gamestate_update_active_state(delta, input)`

- [x] Add API to render the active state 

      `cwt.gamestate_render_active_state(delta)`
