### ISSUE TITLE
Rebuild model event system

### ISSUE THREAD

**Issue by Tapsi** [ctomni231/cwtactics#428]
### Description

We need a simpler event system. In this case we're going to use a bridge object that connects UI and model. The model provides some functions that can be overwritten by the UI to react on important model changes without having to read the model directly. Furthermore the model provides some functions in the bridge as service. The UI can call these to make direct changes in the model. This will be the UI API. Everything else will be called in model internal only.

### Tasks

- [x] All events will be merged into the game commands and model functions
- [x] The model invokes functions on the brigde to notify changes
- [x] There is nothing of the old event system left
