### ISSUE TITLE
Implement stateful input module

### ISSUE THREAD

**Issue by Tapsi** [ctomni231/cwtactics#429]
### Tasks

- Input module
  - [x] is_key_pressed(key)
  - [x] is_action_pressed(action)
  - [x] press_key(key)
  - [x] release_key(key)
  - [x] map_key_to_action(key, action)
