### ISSUE TITLE
CWTCore: Game Startup - Main Menu State

### ISSUE THREAD

**Issue by ctomni231** [ctomni231/cwtactics#433]
## State Explanation

The Main Menu state is the heart of the Title Screen, holding access points to all the major areas of the program. This is the hub where players will decide ultimately what they are going to do within the game, and also decide exactly what options are most comfortable to them. The Main Menu state literally holds a really big vertical menu which holds all the options available.

In order to cater to touch users, each screen will have an inner box. The purpose of an inner visible container is so touch users can "go back" by touching the border of the screen. 

There are a few required items this time around
- A state is not visible if it has not been programmed in yet
- There is an image associated with each state (in cases where translation isn't available)
- The menu is contained within an inner box, with priority to images being visible
- If there are too many items, a scroll feature must be implemented 
## Button Functionality

Keyboard:
- [ ] **Up**: Move up a selection
- [ ] **Down**: Move down a selection

Mouse:
- [ ] **Scroll Wheel**: Scroll up and down selections

Touch:
- [ ] **Up (Swipe):** Rapidly move up selections
- [ ] **Down (Swipe):** Rapidly move down a selection
- [ ] **Tap (Un- selected Item):** Select that item on release
- [ ] **Hold (Un- selected item):** Select that item on release
- [ ] **Tap (Selected Item):** Go to state depending on selection on the screen
- [ ] **Hold (Selected Item):** Go to state depending on selection on the screen
- [ ] **Tap (Screen border):** Proceed to _**Loading State (#431)**_

Generic:
- [ ] **Select:** Go to a state depending on selection on screen
- [ ] **Cancel:** Proceed to _**Loading State (#431)**_
## State Helpers

Modules Required:
- [ ] JSlix Graphics Engine (#435)
- [ ] NekoScript Logic Engine

Optional:
- [ ] Music Engine
