### ISSUE TITLE
implement a performance module

### ISSUE THREAD

**Issue by Tapsi** [ctomni231/cwtactics#441]
We should have a structured way to measure the performance of the game. Insteading of using console outputs, we should use an internal object for this. With that we could use performance indicators for certain actions and being not limited to logging actions (e.g. show warning Dialogs when performance slows down).

### Tasks

- [x] implement a logic module
- [x] you can collect timestamps for given id's/groups/names
- [x] start and stop signal will be delivered by module users

**Comment by Tapsi** [comment]
closed by #442
