### ISSUE TITLE
implement debug information panel on every screen of the game

### ISSUE THREAD

**Issue by Tapsi** [ctomni231/cwtactics#465]
We just need important debug information available in every situation. So we should add a trait for a debug panel which contains important information.

### Tasks

- [ ] the debug panel is visible on every screen
- [ ] the debug screen can be hidden or visible
- [ ] visible state can be toggled by user input
- [ ] Needed information in the panel
  - [ ] FPS of the whole game loop
  - [ ] time (in ms) to update all traits
  - [ ] time (in ms) to render all traits
