### ISSUE TITLE
add rendered trait 

### ISSUE THREAD

**Issue by Tapsi** [ctomni231/cwtactics#471]
objects can be rendered. all objects should be rendered by a central mechanic. 

### Tasks 

- [ ] objects can be rendered with a static image or animated with a sprite 
- [ ] uses jslix to render things 
- [x] expects a position 
- [ ] expects a relation (fixed on screen or fixed on map)

**Comment by ctomni231** [comment]
I don’t understand this ticket. Are we defining that we are using a image renderer? Wouldn’t we need tickets to define what an object is before we tackle rendering of those objects?

I suppose an object is the terrain, units, and buildings of the map. If that is the case, some supporting tickets may be helpful

**Comment by ctomni231** [comment]
Thinking about this again, maybe I’m just misunderstanding what functionality traits can cover. At first, I thought it was game object driven, but maybe it covers everything about those objects including file paths and the like. This may be a good thing to discuss on our next meeting

**Comment by Tapsi** [comment]
closed
