### ISSUE TITLE
critical frame detection

### ISSUE THREAD

**Issue by Tapsi** [ctomni231/cwtactics#477]
### Tasks 

- [x] remove tfps variable
- [x] calculate performance state (normal, slow) 
- [x] data is available in state for debug pages
