### ISSUE TITLE
add selectable trait

### ISSUE THREAD

**Issue by Tapsi** [ctomni231/cwtactics#484]
### Tasks

- [ ] Objects with the selectable trait can be marked as selected
- [ ] The cursor determines which object will be selected 
- [ ] Only one object can be selected at the same time
- [ ] ACTION selects objects
- [ ] CANCEL deselects objects 
- [ ] Selection data is persisted in the data model
