### ISSUE TITLE
add ingame menu trait 

### ISSUE THREAD

**Issue by Tapsi** [ctomni231/cwtactics#485]
### Tasks 

- [ ] Opens when ACTION is triggered 
- [ ] Provides "addEntry" service for other modules 
- [ ] Shows entries from the data model (menu data model) 
- [ ] When active :
  - [ ] Closes when CANCEL is triggered
  - [ ] Closes and persists the selected entry in the data model 
- [ ] Flushes entry data model when closes

...TBD...
